### ISSUE TITLE
Suggestion: using wallpapers as backgrounds

### ISSUE THREAD

**Issue by metakirby5** [97-109-107/whizkers-server#4]
As the title says - for each "tile," it would be neat to see the wallpaper underneath (probably with a transparent overlay to increase visibility).

**Comment by metakirby5** [comment]
I did something similar for the [colorz2](https://github.com/metakirby5/colorz2) preview functionality.

**Comment by 97-109-107** [comment]
I never employed a template engine to change my wallpaper. However, adding this in wouldn't be difficult, but I'm wondering what would make more sense:
- Assuming that the yaml file has a variable called _background_(?) the points to a file. 
  
  or
- Picking up any file path that points to a file extension assumed to be a picture and display it in the relevant row of the template

Can anybody chip in?

**Comment by metakirby5** [comment]
Here are two options I think would make sense:
- Auto-detect background by scanning the yaml file for anything ending in jpg, png, etc.
- Provide a command-line flag to explicitly define what name the background filepath is bound to

You could also combine the best of both worlds: use an explicit flag, but use auto-detect as a fallback, and provide a flag to disable it altogether.
