### ISSUE TITLE
Clicking "Apply" does not work when templates are within nested folder.

### ISSUE THREAD

**Issue by fullsalvo** [97-109-107/whizkers-server#6]
As the title states, the application of other templates does not function correctly when using nested schemes. It assumes that they are all in the base `variable_sets` directory.

**Comment by 97-109-107** [comment]
I'm surprised that doesn't work, all I'm doing is

```
print("Received request for " + theme)
call([command_load, theme])
```

Where `theme` is the name of the template file sans the extension and `command_load` is `whizkers`. So if you visit `http://localhost:9696/?theme=cloudy` it effectively does `whizkers cloudy`

According to the readme file in the example folder, this should work even if `cloudy.yaml` is nested in a folder ([see second last sentence of the linked paragraph](https://github.com/metakirby5/whizkers/blob/master/example/README.rst#additional-usage-information))

Could @metakirby5 chip in? Am I overlooking something?

**Comment by fullsalvo** [comment]
`whiskers`' behavior for nested variable sets is to include the subdirectory as part of the argument for variable sets (e.g. `whizkers themes/foo`). This behavior was part of my motivation for [rhisk](https://github.com/fullsalvo/wz-utils/blob/master/rhisk), which requires only basenames.

**Comment by metakirby5** [comment]
Confirming that you need to include subdirectory in the argument, otherwise you could not distinguish between `foo/theme` and `bar/theme`. You should be calling whizkers using the `fullpath` key in your `output` dict.
